/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PedraPapelTesoura;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DirtHune
 */
public class PedraPapelTesoura extends javax.swing.JFrame {
    String nomeJogadorEscolha, nomeIaEscolha;
        int escolhaMaq, jogadorVitoria, iaVitoria, jogadorDerrota, 
                iaDerrota, empate;
        boolean infinito;
    
    /**
     * Creates new form PedraPapelTesoura
     */
    public PedraPapelTesoura() {
        initComponents();
        setTitle("Jokenpo Game");
    }
    
    public JLabel escolhaIaLabel = new JLabel();
    public JLabel jogadaAtualLabel = new JLabel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        papelMiniaturapng = new javax.swing.JLabel();
        pedraMiniaturapng = new javax.swing.JLabel();
        tesouraMiniaturapng = new javax.swing.JLabel();
        finalizarbtn = new javax.swing.JButton();
        vocetxt = new javax.swing.JLabel();
        iatxt = new javax.swing.JLabel();
        playerVitoriastxt = new javax.swing.JLabel();
        computadorVitoriastxt = new javax.swing.JLabel();
        infinitobtn = new javax.swing.JCheckBox();
        vocetxt1 = new javax.swing.JLabel();
        empatetxt = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        papelMiniaturapng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel_miniatura.png"))); // NOI18N
        papelMiniaturapng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        papelMiniaturapng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                papelMiniaturapngMouseClicked(evt);
            }
        });

        pedraMiniaturapng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedra_miniatura.png"))); // NOI18N
        pedraMiniaturapng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pedraMiniaturapng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedraMiniaturapngMouseClicked(evt);
            }
        });

        tesouraMiniaturapng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tesoura_miniatura.png"))); // NOI18N
        tesouraMiniaturapng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tesouraMiniaturapng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tesouraMiniaturapngMouseClicked(evt);
            }
        });

        finalizarbtn.setText("FECHAR");
        finalizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarbtnActionPerformed(evt);
            }
        });

        vocetxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vocetxt.setForeground(new java.awt.Color(0, 153, 102));
        vocetxt.setText("PLAYER");

        iatxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        iatxt.setForeground(new java.awt.Color(255, 0, 51));
        iatxt.setText("COMPUTADOR");

        playerVitoriastxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        playerVitoriastxt.setText("0");

        computadorVitoriastxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        computadorVitoriastxt.setText("0");

        infinitobtn.setText("Infinito");
        infinitobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infinitobtnActionPerformed(evt);
            }
        });

        vocetxt1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vocetxt1.setText("EMPATE");

        empatetxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        empatetxt.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(iatxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pedraMiniaturapng)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finalizarbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vocetxt1)
                                    .addComponent(papelMiniaturapng))
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(vocetxt))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(tesouraMiniaturapng))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(infinitobtn)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(computadorVitoriastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244)
                .addComponent(playerVitoriastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vocetxt)
                    .addComponent(iatxt)
                    .addComponent(vocetxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerVitoriastxt)
                    .addComponent(computadorVitoriastxt)
                    .addComponent(empatetxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tesouraMiniaturapng)
                                .addGap(6, 6, 6))
                            .addComponent(pedraMiniaturapng, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(papelMiniaturapng, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(finalizarbtn)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infinitobtn)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void computarLogica() {
        if ((nomeJogadorEscolha.equals("PEDRA") && nomeIaEscolha.equals("TESOURA")) ||
                (nomeJogadorEscolha.equals("PAPEL") && nomeIaEscolha.equals("PEDRA")) ||
                (nomeJogadorEscolha.equals("TESOURA") && nomeIaEscolha.equals("PAPEL"))) {
            jogadorVitoria++;
            playerVitoriastxt.setText(String.valueOf(jogadorVitoria)); 
            // Possibilidades de vitória do jogador
            
            melhorDeTres();
            
        } else if ((nomeIaEscolha.equals("PEDRA") && nomeJogadorEscolha.equals("TESOURA")) ||
                (nomeIaEscolha.equals("PAPEL") && nomeJogadorEscolha.equals("PEDRA")) ||
                (nomeIaEscolha.equals("TESOURA") && nomeJogadorEscolha.equals("PAPEL"))) {
            iaVitoria++;
            computadorVitoriastxt.setText(String.valueOf(iaVitoria));
            // Possibilidade de vitória do computador
            
            melhorDeTres();
            
        } else {
            empate++;
            empatetxt.setText(String.valueOf(empate));
            // Empate
            
            melhorDeTres();
        }
    }
    
    public void melhorDeTres() {
        // Método para se o jogo for melhor de três e não infinito
        
        if (infinito == false) {
            
            if (jogadorVitoria > 2) {
                JOptionPane.showMessageDialog(null, "Jogador Venceu!");
                 resetarPontos();
            } else if (iaVitoria > 2) {
                JOptionPane.showMessageDialog(null, "Computador Venceu!");
                resetarPontos();
            } else if (empate > 2) {
                JOptionPane.showMessageDialog(null, "Empate, que sorte!");
                resetarPontos();
            }
            
        } 
        
    }
    
    public void resetarPontos() {
        // Metódos que reseta o placar
        
        jogadorVitoria = 0;
        playerVitoriastxt.setText(String.valueOf(jogadorVitoria)); 
        iaVitoria = 0;
        computadorVitoriastxt.setText(String.valueOf(iaVitoria));
        empate = 0;
        empatetxt.setText(String.valueOf(empate));
    }
    
    public void posicionarJogada() {
        // Posiciona a imagem de acordo com a escolha do computador
        
        getContentPane().setLayout(null);
        
        if(escolhaIaLabel != null) {
            getContentPane().remove(escolhaIaLabel);
        }
        
        escolhaIaLabel.setText(""); 
        escolhaIaLabel.setIcon(new ImageIcon(getClass().getResource("/img/" + nomeIaEscolha + "_invertido.png"))); 
    
        escolhaIaLabel.setBounds(80, 150, escolhaIaLabel.getPreferredSize().width, escolhaIaLabel.getPreferredSize().height);
        getContentPane().add(escolhaIaLabel);
            
        revalidate();
        repaint();
    }
    
    public String escolherJogadaIa() {
        // Escolhe a jogada do computador
        
        escolhaMaq = 1 + (int)(Math.random() * 3);
        
        switch (escolhaMaq) {
            case 1: 
            nomeIaEscolha = "PEDRA"; break;
            
            case 2: 
            nomeIaEscolha = "PAPEL"; break;
            
            default: 
            nomeIaEscolha = "TESOURA";
        }
        
        return nomeIaEscolha;
    }
    
    public void verificarImagem() {
        // Método que redefine a imagem antiga pela nova
        
        if (jogadaAtualLabel != null) {
        getContentPane().remove(jogadaAtualLabel);
        }
    }
    
    public void inserirImagemJogador(String nomeJogadorEscolha) {
        // Método que insere a imagem do jogador
        
        jogadaAtualLabel.setText("");
        jogadaAtualLabel.setIcon(new ImageIcon(getClass().getResource("/img/"+nomeJogadorEscolha+".png"))); 
        
        jogadaAtualLabel.setBounds(450, 150, jogadaAtualLabel.getPreferredSize().width, jogadaAtualLabel.getPreferredSize().height);
        getContentPane().add(jogadaAtualLabel);
    }
    
    private void papelMiniaturapngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papelMiniaturapngMouseClicked
        nomeJogadorEscolha = "PAPEL";
        nomeIaEscolha = escolherJogadaIa();
        
        verificarImagem();
        
        inserirImagemJogador(nomeJogadorEscolha);
        
        posicionarJogada();
        
        computarLogica();
    }//GEN-LAST:event_papelMiniaturapngMouseClicked

    private void pedraMiniaturapngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedraMiniaturapngMouseClicked
        nomeJogadorEscolha = "PEDRA";
        nomeIaEscolha = escolherJogadaIa();
        
        verificarImagem();
        
        inserirImagemJogador(nomeJogadorEscolha);
        
        posicionarJogada();
        
        computarLogica();
    }//GEN-LAST:event_pedraMiniaturapngMouseClicked

    private void tesouraMiniaturapngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tesouraMiniaturapngMouseClicked
        nomeJogadorEscolha = "TESOURA";
        nomeIaEscolha = escolherJogadaIa();
        
        verificarImagem();
        
        inserirImagemJogador(nomeJogadorEscolha);
        
        posicionarJogada();
        
        computarLogica();
    }//GEN-LAST:event_tesouraMiniaturapngMouseClicked

    private void finalizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_finalizarbtnActionPerformed

    private void infinitobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infinitobtnActionPerformed
        infinito = infinitobtn.isSelected();
    }//GEN-LAST:event_infinitobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedraPapelTesoura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel computadorVitoriastxt;
    private javax.swing.JLabel empatetxt;
    private javax.swing.JButton finalizarbtn;
    private javax.swing.JLabel iatxt;
    private javax.swing.JCheckBox infinitobtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel papelMiniaturapng;
    private javax.swing.JLabel pedraMiniaturapng;
    private javax.swing.JLabel playerVitoriastxt;
    private javax.swing.JLabel tesouraMiniaturapng;
    private javax.swing.JLabel vocetxt;
    private javax.swing.JLabel vocetxt1;
    // End of variables declaration//GEN-END:variables
}
